//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWinform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWinform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0a29e3989a45ebfd01f0aaace7265b03 {
            get {
                object obj = ResourceManager.GetObject("0a29e3989a45ebfd01f0aaace7265b03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3f5c76d103b01b78a8fddf3073560f94 {
            get {
                object obj = ResourceManager.GetObject("3f5c76d103b01b78a8fddf3073560f94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carol_Danvers_Iron_Man_Ultron_Hulk_Marvel_Comics__avengers_logo__Marvel_Avengers_logo__marvel_Avengers_Assemble__avengers__text_png {
            get {
                object obj = ResourceManager.GetObject("Carol Danvers Iron Man Ultron Hulk Marvel Comics, avengers logo, Marvel Avengers " +
                        "logo, marvel Avengers Assemble, avengers, text png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carol_Danvers_Iron_Man_Ultron_Hulk_Marvel_Comics__avengers_logo__Marvel_Avengers_logo__marvel_Avengers_Assemble__avengers__text_png_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Carol_Danvers_Iron_Man_Ultron_Hulk_Marvel_Comics__avengers_logo__Marvel_Avengers_" +
                        "logo__marvel_Avengers_Assemble__avengers__text_png-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carol_Danvers_Iron_Man_Ultron_Hulk_Marvel_Comics__avengers_logo__Marvel_Avengers_logo__marvel_Avengers_Assemble__avengers__text_png_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("Carol_Danvers_Iron_Man_Ultron_Hulk_Marvel_Comics__avengers_logo__Marvel_Avengers_" +
                        "logo__marvel_Avengers_Assemble__avengers__text_png-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
